from PyQt6.QtCore import Qt

# Debug flag
DEBUG = True

# Window
WINDOW_TITLE = "Microscope Control System"
WINDOW_X = 100
WINDOW_Y = 100
WINDOW_WIDTH = 1600
WINDOW_HEIGHT = 900
SIDEBAR_WIDTH = 250

# Layout
DEFAULT_SPLITTER_SIZES = {
    "top": [WINDOW_WIDTH // 3, WINDOW_WIDTH // 3],
    "main": [WINDOW_HEIGHT // 2, WINDOW_HEIGHT // 2],
}

# UI Styling & Widget Sizing
BUTTON_HEIGHT = 30
SPINBOX_WIDTH = 120
DOUBLE_SPINBOX_WIDTH = 120
GRAPHICS_VIEW_MIN_HEIGHT = 400
MIN_WIDGET_HEIGHT = 200

# Zoom
ZOOM_IN_FACTOR = 1.25
ZOOM_OUT_FACTOR = 0.8
ZOOM_MIN_LEVEL = -10
ZOOM_MAX_LEVEL = 10

# ROI
ROI_PEN_COLOR = Qt.GlobalColor.red
ROI_PEN_WIDTH = 2
ROI_BRUSH_COLOR = Qt.GlobalColor.transparent
ROI_MIN_SIZE = 5
DEFAULT_ROI_X = 0.0
DEFAULT_ROI_Y = 0.0
DEFAULT_ROI_W = 100.0
DEFAULT_ROI_H = 100.0
ROI_SIZE_MIN = 1
ROI_SIZE_MAX = 2000

# Labels & Text
COORD_LABEL_INITIAL_TEXT = "X: 0.00, Y: 0.00"
MOUSE_POS_LABEL_TEXT = "Mouse Position:"
CLEAR_ROI_BUTTON_TEXT = "Clear ROI"
ZOOM_IN_BUTTON_TEXT = "+"
ZOOM_OUT_BUTTON_TEXT = "-"

# Scanning Parameters
DEFAULT_STEP_SIZE_X = 1.0
DEFAULT_STEP_SIZE_Y = 1.0
MOTOR_STEP_RANGE_MIN = 0.1
MOTOR_STEP_RANGE_MAX = 100.0
MOTOR_XY_RANGE_MIN = -1000
MOTOR_XY_RANGE_MAX = 1000
MOTOR_SETTLE_TIME_SEC = 0.5


# Raman / Spectrometer
SPECTRUM_MAX_WAVENUMBER = 4000
RAMAN_MIN_LIMIT = 0.0
RAMAN_MAX_LIMIT = 4000.0

# Spectrometer Simulation
SPECTRUM_WAVELENGTH_START = 0
SPECTRUM_WAVELENGTH_END = 4000
SPECTRUM_NUM_POINTS = 1000
SPECTRUM_NOISE_FLOOR = 0.1

# Camera Hardware (General)
EXPOSURE_MIN = 100
EXPOSURE_MAX = 1_000_000
EXPOSURE_DEFAULT = 10_000
GAIN_MIN = 0
GAIN_MAX = 300
GAIN_DEFAULT = 100
CAMERA_IMAGE_WIDTH = 800
CAMERA_IMAGE_HEIGHT = 600

# ToupCam-Specific
TOUPCAM_AUTO_EXPO_ENABLED = False
TOUPCAM_DEFAULT_EXPO_TIME_US = 10000
TOUPCAM_DEFAULT_EXPO_AGAIN = 100
TOUPCAM_SNAP_WAIT_SECONDS = 0.3
TOUPCAM_PIXEL_FORMAT_BITS = 24
TOUPCAM_IMAGE_FORMAT = "RGB888"

# Heatmap & Plotting
PLOT_DPI = 100
HEATMAP_CMAP = "viridis"
HEATMAP_ORIGIN = "lower"
HEATMAP_ASPECT = "auto"
X_LABEL_TEXT = "X Position (μm)"
Y_LABEL_TEXT = "Y Position (μm)"
SAMPLE_TITLE = "Sample Heatmap"
LIVE_TITLE = "Intensity Heatmap"
SAMPLE_X_RANGE = (-2.0, 2.0)
SAMPLE_Y_RANGE = (-2.0, 2.0)
SAMPLE_GRID_SIZE = 50

# Output
PICKLE_FILENAME = "scan_data.pkl"

# Threading
THREAD_POOL_SIZE = 4